### ISSUE TITLE
When you merge more tickets are not merged in admin side

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#231] opened 2015-05-01 11:30 UTC
I tried to see this in your demo but i can't see in your demo Merge options.

In my install i had merged 3 tickets and when i open in admiin side i can see only one ticket and not the other. Other ticket can be viewed only in client side not in admin.

So after you merge a ticket you loose the other ticket in admin side.

**Comment by PeopleInside** [comment] 2015-05-01 11:32
Other error is in client dide where there is no status showed. Status are blank.

**Comment by PeopleInside** [comment] 2015-05-01 11:41
If after merged the ticket you send a reply to the ticket than other message of other ticket will be showed.

Also i don't know if is normal in client side image are not showed as preview but only link. In admin side you can see also preview.

**Comment by mkoch227** [comment] 2015-05-01 14:11
I'm able to merge multiple tickets into one on the admin side without any problems. The messages get merged together and the audit trail indicates which tickets were merged:

![capture](https://cloud.githubusercontent.com/assets/333430/7431102/431990d0-efe9-11e4-9928-96f063acb440.PNG)

Here is how HESK performs merges (Mods for HESK has not changed how HESK performs merges in any way):
 - Messages (incl. attachments) are moved into one of the selected ticket tracking IDs
 - Audit trail entries are created for the final ticket tracking ID
 - Other ticket tracking IDs that were part of the merge are added to the final ticket's "merged IDs" property
 - Other tickets that were part of the merge and are not the "final" ticket tracking ID are _deleted_

The status being blank is a minor issue and will be resolved in 2.3.0. In the meantime users can simply copy and paste the ticket ID that appears on the top, go back to the homepage, and paste in that ticket ID.

![capture](https://cloud.githubusercontent.com/assets/333430/7431159/bcb0024e-efe9-11e4-8bd3-59feaf893cde.PNG)

And finally, about attachments: I intentionally only changed the admin-side as it wasn't completely stable at the time. I may implement the new attachments view on the client-side as well at some point, but it's not high on my priority list.

**Comment by PeopleInside** [comment] 2015-05-01 14:13
Any ticket must have an JPG attachments.

In my system 3 ticket opened each one with one or two picture JPG as attachments.
When i merge this three tickets in one and open it on admin side I'M unable to see all ticket but only one.

**Comment by mkoch227** [comment] 2015-05-01 14:33
Ok, so I created three tickets, each with a single JPG file attached. I then merged the three together, opened the one, and here's what I see:

![capture](https://cloud.githubusercontent.com/assets/333430/7431532/70906a30-efed-11e4-8ec5-23959413f9a5.PNG)

All attachments were transferred without any problems from the other two tickets.

**Comment by PeopleInside** [comment] 2015-05-01 14:41
Ok so i don't know.
Unable to reproduce this :) OK.  ^_^

--
Marco Borla
www.PeopleInside.IT www.MarcoBorla.IT

Inviato da dispositivo mobile. | Sended  by mobile device
Il 01/Mag/2015 16:33, "Mike Koch" <notifications@github.com> ha scritto:

**Comment by bastiaanc** [comment] 2015-05-05 09:34
I am sorry to say so, but I had this issue lately. I was not sure why but I just copied it manually. I was trying to reproduce this behavior, but I am not able to.
I do not remember anymore how the setting / statuses or anything were.
I only wanted to say that I (only 1 time) have seen this too.
All I can say that both tickets were extremely large with a lot of info.
As soon as I see it again I will report.

**Comment by PeopleInside** [comment] 2015-05-05 09:45
Thanks. Maybe ticket status merged should have different statues. Sorry I'm unable for now to reproduce too but i had see this as you. Thanks for your precious report. So my report is not wrong.. just only complicate to reproduce. 

Need diagnostic.

**Comment by mkoch227** [comment] 2015-05-11 23:45
I'm still not able to reproduce this issue. If you can provide a step-by-step way to reproduce this without fail, please post it here. Otherwise I'll just leave this issue as-is.

**Comment by mkoch227** [comment] 2015-06-30 01:16
I'm closing this for now. If you're able to reproduce this again in the future, feel free to re-open it.

**Comment by mkoch227** [comment] 2015-08-13 20:36
It appears that the steps to reproduce this (as well as fixing it) have been found! See the email I got below for more information:

> Hi Mike,
>
> regarding the issue #231 submitted by @PeopleInside 
PeopleInside I came across today, I can tell you that I sent a bug report to Klemen Stirn some time in  June after having the same problem and found it beeing present in Hesk up to version 2.6.4 without Mods as well – so, it's not a problem with MFH, but with Hesk.
> I managed to reproduce the issue by the steps below (taken from my mail to Klemen):

> > by accident I spotted a little bug in HESK today (tested with 2.6.2 and 2.6.4).
> > To reproduce follow these steps:

> >  - Customer submits two tickets (“first” and “second”, see
> > screenshots) via customer interface or email
> > - Admin opens the second one and replies to it (“reply to second”),
and then goes back to Home (View all tickets)
> > - Customer opens the second ticket and replies as well (“customer reply to second”)
> > - Admin now merges the two tickets in Home, BEFORE opening one of them again

> > -> If Admin now opens the merged ticket, only the very first entry (“first”) will show up in the merged ticket. Page reload will not help. I can see all the replies to the second ticket in the db at hesk_replies and their "replyto" is correctly set to the id of the merged ticket, but they will not be displayed.
> > -> If now the Customer looks at his ticket again (reload of his open ticket page OR using email link), he will see all the correctly merged ticket contents, while the Admin still won’t be able to see it, regardless of reloads, logout/login etc.
> > -> Only if Admin OR Customer REPLY ONCE MORE to the ticket now, the Admin will be able to see all the merged contents again correctly – otherwise, the data will be sort of "lost" for the Admin. Although there is no actual data loss, the Admin will "miss" the Customer's response.

> > I think this should be corrected if possible.

> Klemen already identified a missing dot in Hesk's admin_functions.inc.php causing this issue, sent me a corrected file and told me that the corrected file will be available with the next version of Hesk (2.6.5?).
> I corrected the admin_functions of my MFH installation manually as well an found it working fine after the fix (line 276 of MFH's admin_functions: it should read "$replies_sql .=" instead of "$replies_sql =" at the beginning of that line).
> 
> So, I think you can "regularily" close the issue when Hesk 2.6.5 will be published, but you might want to correct the admin_functions in your current release? (and release @PeopleInside from his pain...  ;-)  )

Since I'm unusure when the next version of HESK is going to be released, I will add this fix into Mods for HESK 2.4.0.

**Closed** 2015-08-13 21:28 UTC
Labels: original bug, waffle:in progress
